# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from NameModeWindow import Ui_NameModeWindow
from SymbolsModeWindow import Ui_SymbolsModeWindow
from AtomicNumberModeWindow import Ui_AtomicNumberModeWindow

class Ui_MainWindow(object):
    def openAtomicNumberModeWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_AtomicNumberModeWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        MainWindow.hide()

    def openNameModeWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_NameModeWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        MainWindow.hide()

    def openSymbolsModeWindow(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_SymbolsModeWindow()
        self.ui.setupUi(self.window)
        self.window.show()
        MainWindow.hide()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 800)
        MainWindow.setMaximumSize(QtCore.QSize(1000, 800))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-image: url(:/images/Elementium - MainWindow.png);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.SymbolsModeButton = QtWidgets.QPushButton(self.centralwidget)
        self.SymbolsModeButton.setGeometry(QtCore.QRect(420, 300, 131, 51))
        self.SymbolsModeButton.setStyleSheet("font: 12pt \"Autumn\";\n"
"color: rgb(255, 255, 255);")
        self.SymbolsModeButton.setObjectName("SymbolsModeButton")
        self.AtomicNumberModeWindow = QtWidgets.QPushButton(self.centralwidget)
        self.AtomicNumberModeWindow.setGeometry(QtCore.QRect(560, 300, 141, 51))
        self.AtomicNumberModeWindow.setStyleSheet("font: 12pt \"Autumn\";\n"
"color: rgb(255, 255, 255);")
        self.AtomicNumberModeWindow.setObjectName("AtomicNumberModebutton")
        self.NameModeWindowButton = QtWidgets.QPushButton(self.centralwidget)
        self.NameModeWindowButton.setGeometry(QtCore.QRect(280, 300, 131, 51))
        self.NameModeWindowButton.setStyleSheet("font: 12pt \"Autumn\";\n"
"color: rgb(255, 255, 255);")
        self.NameModeWindowButton.setObjectName("NameModeWindowButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #Send signal for open windows function.
        self.NameModeWindowButton.clicked.connect(self.openNameModeWindow)
        self.SymbolsModeButton.clicked.connect(self.openSymbolsModeWindow)
        self.AtomicNumberModeWindow.clicked.connect(self.openAtomicNumberModeWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Elementium"))
        self.SymbolsModeButton.setText(_translate("MainWindow", "Symbols"))
        self.AtomicNumberModeWindow.setText(_translate("MainWindow", "Atomic Number"))
        self.NameModeWindowButton.setText(_translate("MainWindow", "Name"))
import images_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
